# netlify.toml
[build]
base    = "app"          # your Vite app lives here
command = "npm ci && npm run build"
publish = "dist"     # Vite output

# Single-page app routing
[[redirects]]
from = "/*"
to   = "/index.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
